services:
  - type: web
    name: judicont-contabilidad
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      bash -c "python manage.py migrate &&
      echo \"from django.contrib.auth import get_user_model;
      User = get_user_model();
      User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin123')\" | python manage.py shell &&
      gunicorn sistema_contable.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: judicont-db
          property: connectionString
